services:
  postgres:
    image: postgres:15
    container_name: fraud_postgres
    restart: always
    environment:
      POSTGRES_DB: frauddb
      POSTGRES_USER: frauduser
      POSTGRES_PASSWORD: fraudpass
    ports:
      - "5432:5432"
    volumes:
      - fraud_pg_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: fraud_api
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: frauddb
      DB_USER: frauduser
      DB_PASSWORD: fraudpass
      DB_PORT: "5432"
      CORS_ORIGINS: "http://localhost:5173,http://localhost"
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: fraud_dashboard
    depends_on:
      - api
    ports:
      - "5173:80"

volumes:
  fraud_pg_data:
